#!/bin/bash

# initializing variables {{{
multiply_factor=8
current_brightness=$(cat /sys/class/backlight/amdgpu_bl0/brightness)
max_brightness=$(cat /sys/class/backlight/amdgpu_bl0/max_brightness)
current_level=$(( $current_brightness / $multiply_factor ))
max_level=$(($max_brightness / $multiply_factor))
brightness=0
#}}}

set_brightness() { #{{{
  # To check if brightness is not equal to zero or greater than maximum limit
  [[ $1 -gt 0 && $1 -le $max_brightness ]] && echo "$1" > /sys/class/backlight/amdgpu_bl0/brightness || echo Brightness too low.
  pkill -RTMIN+11 i3blocks
} #}}}

# set the brightness at a certain level
if [[ $1 == 'set' ]];then
  brightness=$(( $multiply_factor * $2 ))
  set_brightness "$brightness"

# Increment or decrement brightness
elif [[ $1 =~ -?[0-9]+ ]];then 
  # set brightness to 1 if current_level bet. 0 and multiply_factor and decrementing
  if [[ $1 -lt 0 && $current_level -le $(( $1 * -1 )) && $current_level -gt 1 ]];then
    brightness=$multiply_factor
  # If brightness is less than or equal to 1 and decrementing then step down by 1/4 of multiply_factor untill current_brightness becomes 0
  elif [[ $current_level -le 1 && $1 -lt 0 ]];then
    brightness=$(($current_brightness - $(printf "%.0f" $(echo "0.25*$multiply_factor" | bc))))
  # If brightness is equal to 0 and incrementing then step up by 2/4 of multiply_factor untill current_brightness becomes equal to 1
  elif [[ $current_level == 0 ]];then
    brightness=$(($current_brightness + $(printf "%.0f" $(echo "0.25*$multiply_factor" | bc))))
  elif [[ $current_level == 1 && $current_level -lt $1 ]];then
    brightness=$(($1 * $multiply_factor))
  # set brightness to max if max_level - current_level is less than the increment
  elif [[ $(( $max_level - $current_level )) -lt $1 ]];then
    brightness=$max_brightness
  else
    # Uses signed value to increment or decrement the brightness (also accepts floating point values) 
    brightness=$((($current_brightness + $(printf "%.0f" $(echo "$1*$multiply_factor" | bc)))))
  fi
  set_brightness $brightness
else
  echo Current brightness: $(cat /sys/class/backlight/amdgpu_bl0/brightness)
  echo 'Current level : ' $current_level
fi
