#!/bin/sh

choices="laptop\nlaptopdual\nVGA\nHDMI\nManual selection"

chosen=$(echo -e "$choices" | dmenu -i)

case "$chosen" in
	laptopdual) xrandr --output eDP --auto --output HDMI-A-0 --auto --right-of eDP ;;
	laptop) xrandr --output eDP --auto --output HDMI-A-0 --off ;;
	VGA) xrandr --output VGA-1 --auto --output LVDS-1 --off ;;
	HDMI) xrandr --output HDMI-A-0 --auto --output eDP --off ;;
	"Manual selection") arandr ;;
esac

# Relaunch polybar if there was a selection.
#[ "$chosen" == "" ] || polybar_launch
