#!/bin/bash

curdir=$( pwd )

help(){
	echo -e "Converts a video file using timecode.
Options are:
 -v [video file]
 -t [timecode file]
 -o [output file]
 -h for this help message"

}

while getopts ":hv:t:o:i:" arg; do
	case $arg in
		v) videoFile=$OPTARG;;
		t) timecodes=$OPTARG;;
		o) pdfFile=$OPTARG;;
		h) help ; exit 1 ;;
		*) echo "Invalid Option" ; help;;
	esac
done

#printf "%0$(echo $padding2)g" $iter

imgNum=1
[[ ! -z $timecodes ]] && [[ -f $timecodes ]] && timeCodes=$( cat ${timecodes} ) || timeCodes=$timecodes
numOfImages=$(echo "$timeCodes" | wc -w)
padding=${#numOfImages}
tmpdir="/tmp/vitopdf"

[[ ! -d $tmpdir ]] && mkdir $tmpdir

for tcode in $timeCodes;do
	imgFileName=$(printf "%0${padding}g.png" $imgNum)
	ffmpeg -ss "$tcode" -i "$videoFile" -frames:v 1 ${tmpdir}/${imgFileName}
	imgNum=$(( $imgNum + 1 ))
done

img2pdf -S A4 -f into ${tmpdir}/*.png -o $pdfFile

rm ${tmpdir}/*
